### ISSUE TITLE
Outdated text in new group chat notification received from contact

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13587]
# Bug Report

## Problem 
Since explicit joining was removed from group chats when added by contact, and this is essentially not an invitation, but just adding, the text of the notification should also be changed.

#### Expected behavior
Example of the push notification text: [_Your contact name_] added you to group [_Group chat name_]

#### Actual behavior
<img width="325" alt="Screenshot 2022-06-28 at 15 58 02" src="https://user-images.githubusercontent.com/67952253/176197354-04f5df6d-3549-4a98-b9ed-a3b13c43900a.png">

### Reproduction

1. UserA and UserB add to contacts each other
2. UserA enables PNs
3. UserB creates a group chat with UserA
4. UserA checks PNs

### Additional Information

- Status version: nightly 28/06
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
I think this is fixed, Kindly check when you have the time ..
CC: @qoqobolo

**Comment by qoqobolo** [comment]
Hi @ibrkhalil! 
I still can see the old text in notifications for group chats, so I think we should keep this issue open for now.
Unless the notifications are not completely redesigned in a new UI. But in fact it's not fixed yet

<img width="326" alt="Screenshot 2022-10-20 at 10 43 43" src="https://user-images.githubusercontent.com/67952253/196900939-0d7a7e87-d16f-408b-8eba-8f6aa3a98a27.png">

**Comment by ibrkhalil** [comment]
My bad, Done here
https://github.com/status-im/status-go/pull/2909

**Comment by qoqobolo** [comment]
> Done here
https://github.com/status-im/status-go/pull/2909

ah cool! I guess it doesn't need manual testing as it's just one line with a new text, so you can just close this issue once 2909 is merged. 
Thank you!
