### ISSUE TITLE
It is possible to pin already pinned message

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14729]
**Steps:**

1. Open any chat
2. Send a message
3. Pin that message
4. Close chat
5. Re enter the chat
6. Open list of pinned messages by tapping on pinned banner
7. Longtap on pinned message
8. See if unpin option is displayed for that message

**Actual result:** pin instead of unpin option is shown. It is possible perform pin action for already pinned message

**Expected result:** unpin option is displayed

https://user-images.githubusercontent.com/97245802/211273075-cb94c1d8-7d3c-47b0-8506-1e0bc64d00ca.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment]
@cammellos maybe we still can think about including this issue into rc-1? The problem is that after re-entering chat it is impossible to unpin message from "pinned list" as there no option unpin (only pin). Overall pinned messages are broken in pinned list after chat reopening as they miss profile icon of the author, name, timestamp, chat key etc.). Only text of pinned message is shown. 

It is still possible to unpin message directly from chat, but it will be hard to find message in long chat history in order to unpin it. 


https://user-images.githubusercontent.com/97245802/216553973-2a95f821-a748-4f76-b7d2-33fe66c9be34.mp4

**Comment by cammellos** [comment]
> @cammellos maybe we still can think about including this issue into rc-1? The problem is that after re-entering chat it is impossible to unpin message from "pinned list" as there no option unpin (only pin). Overall pinned messages are broken in pinned list after chat reopening as they miss profile icon of the author, name, timestamp, chat key etc.). Only text of pinned message is shown.
> 
> It is still possible to unpin message directly from chat, but it will be hard to find message in long chat history in order to unpin it.
> 
>  telegram-cloud-document-2-5395514758218655662.mp4

 @ibrkhalil had a fix we worked on a couple of days ago, it's a small change, @ibrkhalil did you push the PR?

Though this only fixes "he problem is that after re-entering chat it is impossible to unpin message from "pinned list" as there no option unpin (only pin). "

> Overall pinned messages are broken in pinned list after chat reopening as they miss profile icon of the author, name, timestamp, chat key etc.). 

This is I believe a separate issue, and seems like worth fixing

**Comment by ibrkhalil** [comment]
> > @cammellos maybe we still can think about including this issue into rc-1? The problem is that after re-entering chat it is impossible to unpin message from "pinned list" as there no option unpin (only pin). Overall pinned messages are broken in pinned list after chat reopening as they miss profile icon of the author, name, timestamp, chat key etc.). Only text of pinned message is shown.
> 
> > 
> 
> > It is still possible to unpin message directly from chat, but it will be hard to find message in long chat history in order to unpin it.
> 
> > 
> 
> >  telegram-cloud-document-2-5395514758218655662.mp4
> 
> 
> 
>  @ibrkhalil had a fix we worked on a couple of days ago, it's a small change, @ibrkhalil did you push the PR?
> 
> 
> 
> Though this only fixes "he problem is that after re-entering chat it is impossible to unpin message from "pinned list" as there no option unpin (only pin). "
> 
> 
> 
> > Overall pinned messages are broken in pinned list after chat reopening as they miss profile icon of the author, name, timestamp, chat key etc.). 
> 
> 
> 
> This is I believe a separate issue, and seems like worth fixing

Yes Andrea, I pushed our latest changes to the PR referencing this issue

**Comment by cammellos** [comment]
@pavloburykh this should be ready to be tested then https://github.com/status-im/status-mobile/pull/14787 , it's a small change and should address the issue with `pin` showed instead of `unpin`, thanks @ibrkhalil 
The other issue I believe is still present (pinned messages not showing picture etc), but maybe we can open a separate issue for that?

**Comment by pavloburykh** [comment]
> @pavloburykh this should be ready to be tested then #14787 , it's a small change and should address the issue with `pin` showed instead of `unpin`, thanks @ibrkhalil The other issue I believe is still present (pinned messages not showing picture etc), but maybe we can open a separate issue for that?

got! Thanx @cammellos will log separate issue for missing elements for pinned.
