### ISSUE TITLE
App stucks on QR scanning during sync with Desktop

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17137]
**Preconditions:** User A - desktop user, User B - mobile user

**Steps:** 

1. User A generates scan QR code
2. User B scans QR
3. Observe the result

**Actual result:** User A stucks on QR scanning. Unable to sync mobile - desktop. 

[logcat_sync.log.zip](https://github.com/status-im/status-mobile/files/12464757/logcat_sync.log.zip)
[Status-debug-logs_sync.zip](https://github.com/status-im/status-mobile/files/12464758/Status-debug-logs_sync.zip)

https://github.com/status-im/status-mobile/assets/97245802/e2213a82-11d0-4b19-9344-5cc641c072de

### Additional Information

- Desktop version: Desktop release version 0.14.0-rc.2 or master Aug 25, 2023 (aarch64)  
- Status version: nightly 
- Operating System: Android, iOS

**Comment by cammellos** [comment]
```
t=2023-08-29T09:32:15+0000 lvl=eror msg="handleAccountImagesImpl: failed to write image" error="write tcp 127.0.0.1:41995->127.0.0.1:36080: write: connection reset by peer"
```

```
t=2023-08-29T07:46:05+0000 lvl=eror msg="handleAccountImagesImpl: failed to write image" error="write tcp 127.0.0.1:42849->127.0.0.1:50464: write: broken pipe"
```

seems like the receiver crashed/is not responding

```
08-29 15:13:02.875  6465  6590 I ReactNativeJS: INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"unsupported version '2'\"}", :event :syncing/input-connection-string-for-bootstrapping}
```

**Comment by cammellos** [comment]
@igor-sirotin is having a look

**Comment by cammellos** [comment]
should be fixed with status go upgrade, thanks @igor-sirotin for taking a look

**Comment by igor-sirotin** [comment]
Yep, there was a breaking change I introduced in https://github.com/status-im/status-go/pull/3909. 
The issue should fix with upgrading to status-go `v0.164.0`. Sorry for not opening an issue in mobile repo about upgrading status-go 😞

**Comment by cammellos** [comment]
No worries, as discussed in chat, this should have been probably a non-breaking change, the policy is to avoid breaking if possible, in order to avoid unexpected issues. 
For example in this case, we could have appended the new parameter at the end, we should try to treat the connection string in the same way we use protobuf, and we could break after a period of interop (3/4 months).

i.e 
```
return fmt.Sprintf("%s%s:%s:%s:%s:%s:%s", connectionStringID, v, ips[0], p, k, ek, ips)
```

Also seems like versioning can only be used for signify a breaking change, as client will refuse to connect to previous versions:

```
func (cp *ConnectionParams) validateVersion() error {
	if cp.version <= versioning.LatestConnectionParamVer {
		return nil
	}
	return fmt.Errorf("unsupported version '%d'", cp.version)
}
```

That probably limits any backward compatibility, since if we want to keep compatibility we can't bump it, and we'd have to accept multiple version ad interim, until we finally bump it, that needs to be taken care when changing this value.

cc @Samyoul @qfrank @saledjenic

**Comment by Samyoul** [comment]
Hmmm, thank you for this issue. 🤦 I advocated for this @cammellos and I also implemented connection string versioning.

Perhaps we can keep versioning to describe what to do with data at specific positions in the string. Connection strings only have a single type so versioning is the only method we currently have to discriminate between them. With protobufs we marshal and unmarshal according to message type.

Granted this specific change is not a type change, it is an extension change. So maybe the concept of version in connection strings is wrong, perhaps "connection string type"?

We need to make a few changes to the current ConnectionString validation process, first what you've identified don't return an error if the string version isn't handleable( or even remove the concept of a version?) . Second remove validation on the string parameter count, to allow for extended strings to be parsable.

**Comment by cammellos** [comment]
@pavloburykh could you test this with latest develop and desktop rc please? it should be fixed now (in theory)

thank you

**Comment by churik** [comment]
I'll take it

**Comment by churik** [comment]
Fixed in develop, confirmed

**Comment by churik** [comment]
Bug is reproducible on nightly 01/09/23 (tried IOS > Desktop [RC 8 ](https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.14.x/8/)

[logs (58).zip](https://github.com/status-im/status-mobile/files/12496717/logs.58.zip)

**Comment by cammellos** [comment]
```
INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"failed to connect to any of given addresses. connecting to 'https://10.62.0.188:59585' failed: dial tcp 10.62.0.188:59585: connect: operation timed out; \"}", :event :syncing/input-connection-string-for-bootstrapping}
```

cc @Samyoul @qfrank

**Comment by cammellos** [comment]
t=2023-09-01T09:46:44+0000 lvl=eror msg="error while discovering udp peers"

**Comment by pavloburykh** [comment]
@cammellos @Samyoul @qfrank 

Still reproducible on Android (tested between Android nightly 04 Sep 2023 => Desktop RC [10](https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.14.x/10/))

Here are updated logs

[Status-debug-logs (55).zip](https://github.com/status-im/status-mobile/files/12513741/Status-debug-logs.55.zip)

At the same time a have managed successfully sync IOS nightly => Desktop.

**Comment by qfrank** [comment]
> @cammellos @Samyoul @qfrank
> 
> Still reproducible on Android (tested between Android nightly 04 Sep 2023 => Desktop RC [10](https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.14.x/10/))
> 
> Here are updated logs
> 
> [Status-debug-logs (55).zip](https://github.com/status-im/status-mobile/files/12513741/Status-debug-logs.55.zip)
> 
> At the same time a have managed successfully sync IOS nightly => Desktop.

I saw error from log:
```
msg="error while discovering udp peers" error="route ip+net: netlinkrib: permission denied"
``` 
There was already a [PR](https://github.com/status-im/status-go/pull/3982) @Samyoul opened for this but not merged yet. I can help with [this](https://github.com/status-im/status-mobile/pull/17166)  @pavloburykh cc @churik

**Comment by Samyoul** [comment]
I'm closing this for now as this specific issue seems to be resolved with https://github.com/status-im/status-go/pull/3982 and https://github.com/status-im/status-mobile/pull/17166
