### ISSUE TITLE
[Android] Text jumps in the composer when user types multiline message row by row 

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18537]
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
No text jumping when user types text or tap enter to move cursor to the new row

#### Actual behavior
Text jumps in the composer when user types multiline message row by row 

https://github.com/status-im/status-mobile/assets/147824399/21bf1184-1037-4a8d-84c5-683e89a8257c

### Reproduction

1. Open chat
2. Type multiline message

### Additional Information

- Status version: nightly from the 17 of January
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
The video wasn't uploaded, Can you upload it again please?
Also can you please check if the issue is reproducible on [this](https://github.com/status-im/status-mobile/pull/18221) PR?

**Comment by mariia-skrypnyk** [comment]
> The video wasn't uploaded, Can you upload it again please? Also can you please check if the issue is reproducible on [this](https://github.com/status-im/status-mobile/pull/18221) PR?

Hi @ibrkhalil !

Working on it. I'll let you know!

**Comment by pavloburykh** [comment]
> Also can you please check if the issue is reproducible on [this](https://github.com/status-im/status-mobile/pull/18221) PR?

Hi @ibrkhalil! As you can see this [PR](https://github.com/status-im/status-mobile/pull/18221) is closed and outdated. So, in order @mariia-skrypnyk can check it you need to re-open it, rebase, resolve possible conflicts and trigger fresh PR builds. Thank you.

**Comment by ibrkhalil** [comment]
> > Also can you please check if the issue is reproducible on [this](https://github.com/status-im/status-mobile/pull/18221) PR?
> 
> Hi @ibrkhalil! As you can see this [PR](https://github.com/status-im/status-mobile/pull/18221) is closed and outdated. So, in order @mariia-skrypnyk can check it you need to re-open it, rebase, resolve possible conflicts and trigger fresh PR builds. Thank you.

Done

**Comment by mariia-skrypnyk** [comment]
> The video wasn't uploaded, Can you upload it again please? Also can you please check if the issue is reproducible on [this](https://github.com/status-im/status-mobile/pull/18221) PR?

Hi @ibrkhalil !
Checked on PR you've asked and there I see such behaviour too:


https://github.com/status-im/status-mobile/assets/147824399/1363590c-7b89-4c03-b7e9-7f9d6bab785e

**Comment by ilmotta** [comment]
FYI: Work on the composer is blocked (unless it's really urgent) until simplifications to improve its performance are evaluated by designers (https://github.com/status-im/status-mobile/pull/20125). With the simplified code it will be much easier to fix remaining bugs.

**Comment by ilmotta** [comment]
Me again @mariia-skrypnyk :) Could you double-check this issue is still relevant from a nightly build? The composer has been revamped recently.

**Comment by mariia-skrypnyk** [comment]
Thanks @ilmotta will check.

**Comment by mariia-skrypnyk** [comment]
Hey @ilmotta !
Initially issue was detected on Android.
I've rechecked it there and it doesn't exist anymore in our updated composer! 👏
