### ISSUE TITLE
after upgrading react-native to 0.73.4 `make run-ios` fails the second time you run it

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#18869]
## Problem

1st time executing `make run-ios` works fine.
The next time you do it (while keeping `make run-clojure` untouched) fails with the following error : 

```
[React-RCTFabric] Compiling RCTThirdPartyFabricComponentsProvider.mm
❌ error: Build input file cannot be found: '/Users/siddarthkumar/code/experiments/status-mobile/
node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. 
Did you forget to declare this file as an output of a script phase or custom build rule which 
produces it? (in target 'React-RCTFabric' from project 'Pods')
[React-RCTFabric] Compiling RCTTextInputComponentView.mm
⚠️ Run script build phase 'Bundle React Native code and images' will be run during every build 
because it does not specify any outputs. To address this warning, either add output dependencies 
to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis"
 in the script phase. (in target 'StatusIm' from project 'StatusIm')
 ```
 
 This gets fixed with :  
-  closing existing `make run-clojure` terminal  and then
- `make clean`
- `make run-clojure`
- `make run-ios`

This is a newly introduced problem and was never the case before.
Perhaps we need to evaluate what changed from react-native 0.72 -> 0.73 and modify our iOS build step.

**Comment by siddarthkay** [comment]
This issue happens because `node_modules/react-native/React/Fabric/*` gets generated at build time with `xcodebuild` and when we run `make run-ios` the second time old `node_modules` are copied over and `xcodebuild` doesnt generate these the 2nd time.

Fixed by omitting copying of `node_modules` for any change in `node_modules/react-native/React/Fabric/*`

ref -> https://github.com/status-im/status-mobile/pull/18563/commits/1689f20966055805d71c6f11fd1008d6381a18a0

**Comment by codekojo** [comment]
Facing similar issue

**Comment by dwjpeng** [comment]
any solutions here？ I faced similar prodblem. after upgrading react from 0.69.x to 0.73.6.

> Fabric/RCTThirdPartyFabricComponentsProvider.mm  Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

**Comment by siddarthkay** [comment]
> any solutions here？

In my case I simply observed this file `RCTThirdPartyFabricComponentsProvider.mm`  inside the `node_modules` folder 
It would get cleaned out the second time we would generate a build but was present the first time we would build iOS.

So as you can see in the comments above, I fixed it with this commit -> https://github.com/status-im/status-mobile/commit/1689f20966055805d71c6f11fd1008d6381a18a0 

However, the setup of status-mobile project is very different from your traditional react-native project so what worked for me may not work for you because our project setup could have huge differences.

You should either open a new issue in the react-native repo itself or check for existing issues and ask questions there.

**Comment by Tebrynn** [comment]
I'm on version 0.73.6 but still facing the issue. I cannot even find the file you mentioned on commit

**Comment by siddarthkay** [comment]
Hey @Tebrynn : are you facing this issue with `status-mobile` or with `react-native`?

note: if its your own project that uses `react-native` then please open an issue in the `react-native` [repository](https://github.com/facebook/react-native/issues).
`status-mobile` does not have a traditional `react-native` setup, and the bugs we face/investigate and fix may not apply to other `react-native` projects.
