### ISSUE TITLE
The required popup is not displayed on the device that is syncing with another device multiple times using seed phrase fallback

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21260]
# Bug Report

Follow up: #21090 

### Reproduction
1. Device A1 syncs with Device A.
2. On Device A, click the 'Pair and Sync' button in the sync popup.
3. Device A2 syncs with Device A.

#### Expected behavior:
 A popup [Sync your profile](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3451-12759&node-type=frame&t=xSY9Obm5guQvD38k-0)  is displayed on Device A2.

#### Actual behavior: 
A popup [New device detected](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3451-12926&node-type=frame&t=xSY9Obm5guQvD38k-0) is displayed on Device A2. If a try sync device A3 with device A - the same result.

Video from device A2: 
https://github.com/user-attachments/assets/51d0310e-7524-4856-9d9f-20ecc415cf8e

Screenshots from device A after sync: 
![photo_2024-09-12_13-02-31](https://github.com/user-attachments/assets/98f56fb8-f19e-48f5-bfd2-af7129fb21f8)
![photo_2024-09-12_13-02-28](https://github.com/user-attachments/assets/211f0da8-ccb0-47fc-9113-51f128fed011)

### Additional Information

- Status version: PR build #21090 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
Original report: https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345820848

More details:
https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345841505
https://github.com/status-im/status-mobile/pull/21090#issuecomment-2346491345
https://github.com/status-im/status-mobile/pull/21090#issuecomment-2346494640
https://github.com/status-im/status-mobile/pull/21090#issuecomment-2349134620
https://github.com/status-im/status-mobile/pull/21090#issuecomment-2350002316

**Comment by Parveshdhull** [comment]
~Or wrong notification is fetched - https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345841505~

**Comment by Parveshdhull** [comment]
To summarize, if the account previously used the fallback flow, then on the next recovery—whether through normal syncing or fallback—it might fetch an old pairing message. This could trigger a pair-and-sync notification which was intended for the main device from which we recovered the account

**Comment by qfrank** [comment]
Hi @jrainville , are you working on this? If not yet, I can help.

**Comment by Parveshdhull** [comment]
@qfrank, please avoid working on the issue for now 

@Horupa-Olena, please update this issue once https://github.com/status-im/status-mobile/pull/21298 has been tested. I believe we have mixed two issues here:

- [ ] "More details" notification not shown for the recovering device
 - [ ] "Pair and Sync" notification is shown instead.
 
I think these are two distinct issues. The first one might have been fixed in https://github.com/status-im/status-mobile/pull/21298#issuecomment-2371599349.

So, if only the second issue remains after https://github.com/status-im/status-mobile/pull/21298 is tested, then we can update issue accordingly and proceed.

**Comment by qfrank** [comment]
I'm sure there exist issue on creating notification logic on status-go side, if @jrainville is not working on it, I can help

**Comment by Horupa-Olena** [comment]
@qfrank @Parveshdhull Hi. I'm not finished with #21298 but can say that this issue still reproduce. Also I noticed that old notifications about sync fetched in usual restore for old account (old = account that have few tries to syncs before) flow where we use seed phrase.

**Comment by qfrank** [comment]
Hi @Horupa-Olena ,  I think we can close this issue now as it's solved already?

**Comment by churik** [comment]
@Horupa-Olena reopen if still reproducible
