### ISSUE TITLE
Desktop app crashed and is unable to start anymore

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-react#6584]
Yesterday I've experienced for the first time with Status Desktop that, right after trying to login, the "App quit unexpectedly". After that, the application seems unable to start again. While I can start the Status program, there's no window showing up with the app (basically like running any program on mac but having all windows closed).

I've reinstalled the latest nightly and now luck. After I restarted my machine, I was at least able to get the login screen again. However, same thing, after entering my password to login, the app crashes and I'm exactly where I left off. 

Status version: `https://status-im.ams3.digitaloceanspaces.com/StatusIm-181104-025922-fd5fc6-nightly.dmg`
OS: MacOS 10.13.5 High Sierra

If there's anything else I can do to provide more information that helps debugging this, please let me know!

**Comment by vkjr** [comment]
@PascalPrecht, Status communicates with process called `ubuntu-server`. When app crashes it sometimes doesn't terminate. So you can open Activity Monitor and kill it manually. After that app should start fine.

**Comment by 0x-r4bbit** [comment]
@vkjr thanks! That did the trick! :)

Do we want to keep this open though? I think this is probably not the expected fix to this problem.

**Comment by vkjr** [comment]
@PascalPrecht, I thought we already had issue for this, but can't find it. So lets keep this one.

**Comment by 0x-r4bbit** [comment]
Probably this one? https://github.com/status-im/react-native-desktop/issues/385

**Comment by pedropombeiro** [comment]
Yesterday I fixed a related one: https://github.com/status-im/react-native-desktop/issues/381

**Comment by vkjr** [comment]
@PombeirP, looks like we answering different parts of complex problem :)
@PascalPrecht, the crash you encounter is fixed by @PombeirP already, but problem with `ubuntu-server` process hanging after crash is still around.

**Comment by vitvly** [comment]
There used to be an issue https://github.com/status-im/status-react/issues/5444, which was closed in favor of https://github.com/status-im/status-react/issues/6175

**Comment by vkjr** [comment]
@siphiuel, thanks! So I think this one can be closed.

**Comment by 0x-r4bbit** [comment]
Alright closing this in favour of #6175 as well then

**Comment by 0x-r4bbit** [comment]
Thanks everyone for your quick support!

**Comment by pedropombeiro** [comment]
Reopening this to start a PR to kill rogue ubuntu-server processes at startup.

**Comment by 0x-r4bbit** [comment]
@PombeirP 🎉
