### ISSUE TITLE
Implement designs for sign in screens

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9224]
# Feature Issue

### User Story

As a user, I want to see consistent sign in screens across the app.

### Description
Figma: [Sign In Design](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12)

*Summary*: currently across the app we have different from design login screens and mismatch in them for ordinary accounts and for keycard.

### Acceptance Criteria
For V1 is required from my POV to implement:
- [ ]  flow 1. - [Single account ](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12)
<img width="463" alt="photo_2019-10-16 13 42 51 jpeg 2019-10-16 13-43-43" src="https://user-images.githubusercontent.com/4557972/66916235-1cd4c480-f01b-11e9-9bfb-ab239c19a591.png">

- [ ]  flow 3. - [Multiple accounts ](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12)

Now => should be
<img width="375" alt="diffs" src="https://user-images.githubusercontent.com/4557972/66914520-42f86580-f017-11e9-9e71-210fb8a6aa31.png">

I think we can skip frosen account for now, I don't know should it be implemented in v1 scope or not (cc @guylouis @rachelhamlin )

- [ ]  flow 5. - [Sign in with passcode for keycard](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=5038%3A4)
Now => should be
<img width="423" alt="dsfsddsdsdf" src="https://user-images.githubusercontent.com/4557972/66915456-573d6200-f019-11e9-8403-29db0f9bdf38.png">
Cancel should be replaced with Back button, as for ordinary accounts.

### Notes

I believe we can skip `Trouble sign in?` popup, frozen account and all flows related to biometric for now.
@rachelhamlin please, edit an issue if you think they are required for V1

**Comment by guylouis** [comment]
waouh great point 

What is the screen on the left and the one on the right, is that the difference between design and implementation, or  difference between keycard multiaccount and non-keycard multiaccount ? 

aslo what do you mean by frozen account ?

**Comment by andmironov** [comment]
>aslo what do you mean by frozen account ?

"Frozen accounts" is something I added just recently. An account turns frozen (btw it should be "Frozen key") when the user exceeds the number of attempts to enter the correct passcode.

<img width="826" alt="Screen Shot 2019-10-16 at 17 31 03" src="https://user-images.githubusercontent.com/3115606/66929020-ffafee00-f03a-11e9-867b-e66fcb992d89.png">

A frozen key is still listed in the list of available keys but is greyed out

<img width="407" alt="Screen Shot 2019-10-16 at 17 33 48" src="https://user-images.githubusercontent.com/3115606/66929094-1f471680-f03b-11e9-8f2a-766141d41ec8.png">

After a brief discussion with the design team, we decided to call it "frozen". "Blocked" might refer to something that has happened on behalf of the authority. "Locked" also did not feel right, so we settled on "frozen"

**Comment by churik** [comment]
@guylouis 
1) it is how it looks now vs how it is designed
2) answered by @andmironov , thx

**Comment by hesterbruikman** [comment]
@andmironov @yenda can you confirm flow 1 and 5 in this issue?

Following the same rationale of not showing the key on the multiple accounts (aka `Your keys`) screen, because it might change in the future/is not an accurate representation of the root key, I imagine we also don't want to include it in the single account view. (Currently it is included in flow 1 and 5).

Context: https://github.com/status-im/status-react/issues/8935#issuecomment-529444511

**Comment by andmironov** [comment]
@hesterbruikman  working on a more complete issue about Keycard sign-in with @guylouis to replace a number of smaller issues including this one will be ready next week. WIP https://github.com/status-im/status-react/issues/9264

**Comment by rachelhamlin** [comment]
@guylouis I'm reviewing your WIP #9264 - can we align on which of these issues we're selecting to fix? 

In my opinion, some of these issues are optimizations that can be punted until later, and I'd like to be consistent in fixing issues across keycard + regular screens. I think only issues pertaining to flow 5 should be fixed, because they're inconsistent with the regular screens.

Here's my take on it:

**Issues identified in flow 1 + 3 do not need to be prioritized for v1.**

The changes to the menu elements (`...` replacing the bottom options), the appropriate (reduced) main screen for single accounts, and the account type indicator (keycard icon vs. regular) are all UI optimizations. 

I would like to separate out the lack of key indicator on the unlock screen, though. That to me is a v1 nice-to-have.

![image](https://user-images.githubusercontent.com/15470435/67388096-f4574800-f58f-11e9-906e-8f20781a6fdf.png)

**Frozen account is a feature to be proposed + ranked in objective level roadmap planning.**
So, yes, out of scope.

**Some of the issues in flow 5 do need to be fixed for v1.**
We took the breadcrumbs out of these screens, and that should be the case for keycard as well, so these need to be removed:
![image](https://user-images.githubusercontent.com/15470435/67388328-587a0c00-f590-11e9-9f6a-b59dc2937370.png)

Cancel should be replaced with back button for consistency.
![image](https://user-images.githubusercontent.com/15470435/67388534-c1fa1a80-f590-11e9-81ff-fcb559711224.png)

`Recover key` I can change to `Access key` myself, but I see some other items in [en.json](https://github.com/status-im/status-react/blob/develop/translations/en.json) that use the same word and don't know what they are. @guylouis do you recognize this copy?

```
	"recipient-code": "Enter recipient address",
	"recover": "Recover",
	"recover-key": "Recover key",
	"recover-keycard-multiaccount-not-supported": "Recovering keycard multiaccount with password is not supported",
	"recover-multiaccount-warning": "Your wallet information will be exposed by importing this multiaccount.",
	"recover-password-invalid": "This multiaccount already exists but passwords do not match",
	"recover-password-too-short": "Password is too short",
	"recover-with-keycard": "Recover with Keycard",
	"recovering-key": "Recovering key...",
```

Lastly, what are the different options for the `...` menu at the top of the screen @churik?

**Comment by andmironov** [comment]
@rachelhamlin check out the issues in https://github.com/status-im/status-react/issues/9264, all updated and cleaned up, some new issues added after review. Also this is part of many others https://github.com/status-im/status-react/issues/9365

**Comment by yenda** [comment]
@churik @rachelhamlin @andmironov so is everything in the original issue still relevant and unique to this issue or can some of the scope be removed as already included in other issues?

**Comment by churik** [comment]
I'm not sure about priorities, for me this one sounds like `v1 release`, I'm not sure about other stuff.

**Comment by rachelhamlin** [comment]
Nice and granular. Thank you @guylouis @andmironov! I think we can close this one and replace it with #9264?

**Comment by churik** [comment]
@rachelhamlin #9264 will be in release scope?

**Comment by rachelhamlin** [comment]
@churik I think we should segment it into P0 and P1. Working on it. I think the need to remove breadcrumbs is also missing...

**Comment by churik** [comment]
@rachelhamlin feel free to close this one after prioritizing https://github.com/status-im/status-react/issues/9264
